# Generated by Django 4.2.2 on 2023-07-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapge', '0002_student_prefix_chioces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prefix_chioces',
            new_name='prefix',
        ),
    ]
